name:                hsakamai
version:             0.1.0.1
github:              "junjihashimoto/hsakamai"
license:             BSD3
author:              "Junji Hashimoto"
maintainer:          "junji.hashimoto@gmail.com"
copyright:           "2019 Junji Hashimoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Akamai API(Edgegrid and Netstorage)
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/junjihashimoto/hsakamai#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-conduit
- http-types
- cryptonite
- bytestring
- unix-time
- random
- conduit
- xml-conduit
- text
- memory
- aeson
- uuid
- case-insensitive

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  netstorage:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hsakamai
    - optparse-applicative
    - yaml
    - conduit-extra
    - unix

executables:
  purge:
    main:                PurgeMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hsakamai
    - optparse-applicative
    - yaml
    - conduit-extra
    - unix

tests:
  doctest:
    main: doctests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsakamai
    - doctest

default-extensions:
  - Strict
  - StrictData
